DROP DATABASE IF EXISTS prueba;
CREATE DATABASE IF NOT EXISTS prueba;
USE prueba;

CREATE TABLE IF NOT EXISTS USERS(
    ID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR (50) UNIQUE NOT NULL ,
    PASSWORDS TEXT NOT NULL,
    FIRST_NAME VARCHAR(45),
    SECOND_NAME VARCHAR(100),
    BIRTH_DATE DATE,
    EMAIL VARCHAR(256)
);